name: Docker Image build

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: siddharthalhat001/sdev
          tags: 1.0.0-manual-1
          registry: docker.io
          dockerfile: .
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
